### ISSUE TITLE
Missing Persona2.xcframework.zip in 2.5.5

### ISSUE THREAD

**Issue by gblock92** [persona-id/inquiry-ios-2#3]
Is there a reason why we're missing the **Persona2.xcframework.zip** file from 2.5.5 release?

**Comment by gblock92** [comment]
There's a script I have in my CI Pipeline to upload locally built dsyms and it's failing because it's can't download 
https://github.com/persona-id/inquiry-ios-2/releases/download/2.5.5/Persona2.xcframework.zip

**Comment by jacoblange-dev** [comment]
Thanks for flagging, our post merge pipelines that upload our release to github timed out on this step. I've rebuilt the release and this link should now work https://github.com/persona-id/inquiry-ios-2/releases/download/2.5.5/Persona2.xcframework.zip

**Comment by jacoblange-dev** [comment]
Reopening briefly, rerunning caused the checksums to fail for SPM. Rebuilding the release once more

**Comment by jacoblange-dev** [comment]
ok I think it should all be good now.

**Comment by gblock92** [comment]
I see it now! Thank you 🙂
