### ISSUE TITLE
Themes for Persona

### ISSUE THREAD

**Issue by PomegranateApps** [persona-id/inquiry-ios-2#4]
I'm working on customizing my theme for Persona. I have one issue and one request.

The privacy policy link is using the same color as the `buttonBackgroundColor`. I'm setting it to clear so the privacy policy link is not visible.

![Persona](https://user-images.githubusercontent.com/7399834/221251842-2cb2219a-9404-4abc-aac0-a1d0ea88fc32.png)

Is it possible to have a `textCase` property for the buttons? We want our buttons to be uppercased. The modifier in SwiftUI is `.textCase(.uppercase)`.

**Comment by jacoblange-dev** [comment]
We are moving away from client side themeing on mobile and replacing with server side themeing configured via the Persona Dashboard. Both of these requests are already configurable server side and therefore we won't be adding in new themeing attributes to the client apis. iOS 2.7.0 marks various client side themeing initializers as deprecated as a part of this effort. Please work with your account team if you have questions.

**Comment by PomegranateApps** [comment]
Ok, thank you! I would imagine it would still be the same issues whether the styling is applied on the client or server.

**Comment by PomegranateApps** [comment]
Could you also direct me to where this functionality is on the Persona Dashboard?
