### ISSUE TITLE
Any plans to support swift6 

### ISSUE THREAD

**Issue by PSinha1202** [persona-id/inquiry-ios-2#6]
Not an issue but a question. 

Do you have plans to support swift6 version soon? The reason being we are using the InquiryDelegate inside our viweController which is a @mainActor now and its complaining use of `InquiryDelegate` inside VC. As of now we are work around by making the func nonisolated or have to use @preconcurrency
```
nonisolated
  func inquiryComplete(inquiryId: String, status: String, fields: [String: Persona2.InquiryField]) {
    Task { @MainActor in
      model.inquiryComplete(inquiryId, ..)
    }
  }
```

Since document says `InquiryDelegate`, so might be worth making it @Mainactor?
```
/// Methods for managing verification results.
/// Please note: all methods will be called from the main thread.
```

**Comment by jacoblange-dev** [comment]
hi @PSinha1202 thanks for flagging, we'll investigate if there's api improvements we can safely make here, will follow up if we do make a change.

**Comment by jacoblange-dev** [comment]
Hello, we will conduct a minor release (v2.25.0) early next week with this change.
